@startuml

(*)  --> "Mp4分流"
"Mp4分流" --> "视频解码"
--> "SurfaceTexture处理" as vs_deal
--> 视频预览

vs_deal --> 从Surface上编码视频
--> 媒体保存
"Mp4分流" --> "音频解码"
--> 音频处理
--> 音频编码
--> 媒体保存
-->(*)
音频处理 --> 音频播放

(*) --> 音频采集
--> 音频处理

Mp4分流 --> 音频拷贝
--> 媒体保存

(*) --> 视频采集
视频采集 --> vs_deal
@enduml