@startuml

interface 用户控制点

cloud "" {
用户控制点 .> [媒体入口]
}

cloud "" {
 [音视频合成或播放处理] <.. [视频处理]
 [音频处理] ..> [音视频合成或播放处理]
}

cloud "音频处理" {
音频处理轨迹 <-- [媒体入口]
音频处理轨迹 ->[音频采集]
[音频采集] -> [音频处理]
[音频处理] -> [音频处理完成通知]
}

cloud "视频处理" {
[媒体入口] --> 视频处理轨迹
视频处理轨迹 ->[视频采集]
[视频采集] -> [视频处理]
[视频处理] -> [视频处理完成通知]
}

@enduml