@startuml

cloud "用户目的"{
[媒体文件]
}

cloud "媒体生成器"{
[媒体文件] <-- [媒体生成]
[媒体生成] <-- [数据后处理]
}

cloud "数据采集器"{
[数据后处理] <-- [数据前处理]
[数据前处理] <-- [数据采集]
[数据前处理] . [原始数据修改预览等]
}

cloud "一般为数据编码"{
[数据后处理] . 一般为数据编码
}

cloud "原始数据修改预览等"{
}

cloud "所有要求有上层提，下层做实现\r需要什么数据，上层创建容器，\n下层负责填充"{
}


@enduml